### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/euphoria#1]
Overall documentation for building an Exercism track lives at https://exercism.org/docs/building/tracks/new

This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [x] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [x] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [ ] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
- [x] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [ ] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [ ] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
- [ ] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by axtens** [comment]
One of the OpenEuphoria admins, @jimcbrown , has given [explicit permission](https://openeuphoria.org/forum/137613.wc?last_id=137615) to use the existing [OpenEuphoria icon](https://openeuphoria.org/logos/80x84-mongoose-color-lite.png) for the Euphoria track @kytrinyx @ErikSchierboom

**Comment by axtens** [comment]
[More detaisl](https://openeuphoria.org/wiki/view/LogoLicence.wc) about icon policy from administrator @ghaberek

**Comment by glennj** [comment]
Created PR exercism/snippet-extractor#91

and exercism/tokei#13

**Comment by glennj** [comment]
@axtens the logo's done: it looks like the [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch) step is complete

**Comment by axtens** [comment]
So leave the syntax highlighting till after launch?
